export const CHUNK_SIZE = 8; // gonna be 16 or so
export const CELL_SIZE = 100;
export const MIN_SCALE = 0.5;
export const MAX_SCALE = 2;
export const GRID_LINE_WIDTH = 1;
export const GRID_FONT = `12px sans-serif`;
export const GRID_LINE_STYLE = `#aaf`;
export const GRID_STROKE_STYLE = `#444`;
export const TAP_THRESHOLD = 5;
export const SCALE_STEP = 1.1;
export const EVENT_RETENTION_TIMEOUT = 1000; // ms
