services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_BROWSER: "off"
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    command: server /data
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-minio:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./minio/blocks:/source-blocks:ro
      - ./minio/code:/source-code:ro
      - ./minio/chunks:/source-chunks:ro
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...';
      sleep 5;

      echo 'Setting up MinIO alias...';
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin123;

      echo 'Creating buckets...';
      /usr/bin/mc mb local/blocks --ignore-existing;
      /usr/bin/mc mb local/code --ignore-existing;
      /usr/bin/mc mb local/chunks --ignore-existing;

      echo 'Setting bucket policies...';
      /usr/bin/mc anonymous set download local/blocks;
      /usr/bin/mc anonymous set download local/code;
      /usr/bin/mc anonymous set download local/chunks;

      echo 'Uploading blocks...';
      /usr/bin/mc cp --recursive /source-blocks/ local/blocks/;
      /usr/bin/mc cp --recursive /source-code/ local/code/;
      /usr/bin/mc cp --recursive /source-chunks/ local/chunks/;

      echo 'MinIO initialization completed!';
      exit 0;
      "
    restart: "no"

volumes:
  minio-data:
